# Generated by Django 5.0.6 on 2024-07-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(default='', max_length=50)),
                ('Father_Name', models.CharField(default='', max_length=50)),
                ('Mother_Name', models.CharField(default='', max_length=50)),
                ('Email', models.EmailField(default='', max_length=40)),
                ('Contact', models.CharField(default='', max_length=20)),
                ('Whatsapp_Contact', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=150)),
                ('Date_of_Birth', models.CharField(default='', max_length=20)),
                ('Gender', models.CharField(default='', max_length=15)),
                ('Class', models.CharField(default='', max_length=20)),
                ('Students_Picture', models.FileField(blank=True, default='', max_length=250, null=True, upload_to='form/')),
                ('Father_Picture', models.FileField(blank=True, default='', max_length=250, null=True, upload_to='form/')),
                ('Mother_Picture', models.FileField(blank=True, default='', max_length=250, null=True, upload_to='form/')),
                ('Previos_Year_Marksheet', models.FileField(blank=True, default='', max_length=250, null=True, upload_to='form/')),
                ('Transfer_Certificate', models.FileField(blank=True, default='', max_length=250, null=True, upload_to='form/')),
            ],
        ),
    ]
