# Generated by Django 5.0.6 on 2024-07-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission_form',
            name='Father_Picture',
        ),
        migrations.RemoveField(
            model_name='admission_form',
            name='Mother_Picture',
        ),
        migrations.RemoveField(
            model_name='admission_form',
            name='Previos_Year_Marksheet',
        ),
        migrations.RemoveField(
            model_name='admission_form',
            name='Students_Picture',
        ),
        migrations.RemoveField(
            model_name='admission_form',
            name='Transfer_Certificate',
        ),
    ]
