# Generated by Django 5.0.6 on 2024-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_img', models.FileField(blank=True, default='', max_length=120, null=True, upload_to='faculty/')),
            ],
        ),
    ]
