# Generated by Django 5.0.6 on 2024-07-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Faculty_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Faculty_contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Faculty_degree',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Faculty_email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Faculty_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
