# Generated by Django 5.0.6 on 2024-07-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_faculty_address_faculty_faculty_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Faculty_contact',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Faculty_email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
