# Generated by Django 5.0.6 on 2024-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=15)),
                ('sub', models.CharField(default='', max_length=30)),
                ('t_name', models.CharField(default='', max_length=30)),
                ('Class', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
