# Generated by Django 5.0.6 on 2024-07-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_rename_t_name_table_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='table',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='table',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='table',
            name='period_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='table',
            name='period_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='table',
            name='period_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='table',
            name='period_4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='table',
            name='period_5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='table',
            name='period_6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='table',
            name='period_7',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='table',
            name='period_8',
            field=models.CharField(default='', max_length=100),
        ),
    ]
