# Generated by Django 5.0.6 on 2024-07-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_remove_table_class_remove_table_sub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=15)),
                ('period_1', models.CharField(default='', max_length=100)),
                ('period_2', models.CharField(default='', max_length=100)),
                ('period_3', models.CharField(default='', max_length=100)),
                ('period_4', models.CharField(default='', max_length=100)),
                ('period_5', models.CharField(default='', max_length=100)),
                ('period_6', models.CharField(default='', max_length=100)),
                ('period_7', models.CharField(default='', max_length=100)),
                ('period_8', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
