# Generated by Django 5.0.6 on 2024-07-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_class9'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class9',
            new_name='Class_9',
        ),
    ]
