# Generated by Django 5.0.6 on 2024-07-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_rename_class9_class_9'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class_9',
        ),
    ]
