# Generated by Django 5.0.6 on 2024-07-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_news_news_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_name',
            new_name='news_date',
        ),
        migrations.AddField(
            model_name='news',
            name='news_month',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_des',
            field=models.CharField(default='', max_length=50),
        ),
    ]
