# Generated by Django 5.0.6 on 2024-07-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_news_name_news_news_date_news_news_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_date', models.CharField(default='', max_length=20)),
                ('Event_month', models.CharField(default='', max_length=20)),
                ('Event_des', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
