# Generated by Django 5.0.6 on 2024-07-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
