# Generated by Django 5.0.6 on 2024-07-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_name', models.CharField(default='', max_length=20)),
                ('News_des', models.CharField(default='', max_length=120)),
            ],
        ),
    ]
