# Generated by Django 5.0.6 on 2024-07-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Announcement_name', models.CharField(default='', max_length=200)),
                ('Announcement_des', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
