# Generated by Django 5.0.6 on 2024-07-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
