# Generated by Django 5.0.6 on 2024-07-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='career',
        ),
        migrations.AddField(
            model_name='career',
            name='career_des',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='career',
            name='career_heading',
            field=models.TextField(default=''),
        ),
    ]
