# Generated by Django 5.0.6 on 2024-07-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_remove_career_career_career_career_des_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='career_heading',
            field=models.CharField(default='', max_length=100),
        ),
    ]
